server:
  port: 8001
spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true  # 保证实体对象和数据表时刻保持一致
    show-sql: true  # 显示SQL语句

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{PtxId}] [%thread] %-5level %logger{50} - %msg%n"

#server:
#  ssl:
#    key-store: classpath:jojo.key
#    key-store-password: 123456
#    key-password: 123456

